server {
    listen 8080;
    root /app;

    location / {
        try_files /frontend/$uri /frontend/index.html;
    }

    location /data/ {
        alias /app/data/;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=3600";
    }
}
